### ISSUE TITLE
Collection Banner and Logo not appearing

### ISSUE THREAD

**Issue by DraxIndustries79** [scientist-softserv/hykuup_knapsack#12]
## Story
Collection Banner and Logo images uploaded are not appearing on the show page for that collection.
Example:  https://kevin-test-aug-23.hykuup.com/collections/19b121b2-7a6c-4050-ac9e-448371c622b1?locale=en

![Image](https://user-images.githubusercontent.com/37004183/258185085-26d1bd75-a166-42c6-ad50-0f3bf045a589.png)

## Acceptance
- [ ] Uploaded Collection Banner appears on show page
- [ ] Uploaded Collection Logo appears on show page

## Testing
Upload a logo and a banner for a collection, save, then navigate to public view for that collection landing page.  Logo and Banner should appear.

**Comment by jillpe** [comment]
This was done in UTK and contributed back to hyku

**Comment by kirkkwang** [comment]
Blocked until Rob makes sure all the changes he had to make get consolidated properly

**Comment by ShanaLMoore** [comment]
s33 #238
