### ISSUE TITLE
Hyrax double_combo and 2 failing specs

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/hykuup_knapsack#137]
There are two broken specs regarding how we handle redirects for resources.

The logic we introduced with double_combo allowed us to "show" a Valkyrie resource at it's associated pre-Valkyrie location.

We need to resolve this; I don't know what that yet looks like and need to have a conversation.

**Comment by jillpe** [comment]
The follow up tickets are urgent and need to be high priority
