### ISSUE TITLE
🐛 EDIT AF record with no files on i35

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#157]
# Summary

We are unable to edit/save a pre-existing active fedora record. From brief debugging, it may have something to do with the embargo and changes that occurred between hyrax rc2 and rc3.

## error

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/776154b8-7f0e-42d6-b1c6-bf4a3a435cc6)

## fcrepo dashboard

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/8dd90087-688d-419c-a808-e37595723d2f)

# Acceptance Criteria

- [ ] A user should be able to edit and save a pre-existing ActiveFeora record on i35-valkyrize-hyku.
- [ ] On save, behind the scenes the object should get converted to a valkyrie resource. 

# Steps to reproduce

1. switch to hyku main
2. create a record with no file sets
3. switch to i35-valkyrize-hyku
4. edit and save that record

**Comment by ShanaLMoore** [comment]
Questions: Does this behavior happen from rails console too?

**Comment by kirkkwang** [comment]
fixed with this commit https://github.com/samvera/hyku/commit/21d8e7033b41667aec6d00069d502fbee539ed6c
