### ISSUE TITLE
Mobius: add custom properties to MobiusWork

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/hykuup_knapsack#167]
### Blocked by 
- #166

# Story

Ref:
- #27 
- [Mobius Metadata Mappings spreadsheet](https://docs.google.com/spreadsheets/d/12quM0rKmv6g0Dm83dDKcaKkrnz8lyjxMShAMSVg3Hec/edit#gid=0)

Mobius imports include metadata outside of Hyrax's default properties. To fully support Bulkrax imports, these properties need to be created. 

Mobius has a custom work type (see #166). The properties should only be added to that work type.  

# Acceptance Criteria

- [ ] The `Additional Fields to be Added` in [this spreadsheet](https://docs.google.com/spreadsheets/d/12quM0rKmv6g0Dm83dDKcaKkrnz8lyjxMShAMSVg3Hec/edit#gid=0) have been added to the `MobiusWork` work type 
  - [ ] Rights
  - [ ] Relation
  - [ ] Coverage
  - [ ] File Format 
    - [ ] Property name **cannot** be `format` (conflicts with Hyrax method) 
  - [ ] ~~Community~~
  - [ ] ~~Collection~~

# Testing Instructions and Sample Files

_[Sample files](https://drive.google.com/drive/folders/1VZ5e-6psAPypp77P2AhY-0eOQg14Jpe4)_

1. Login as an admin 
2. Create a tenant with a `mobius` name
3. Navigate to Dashboard > Works 
4. Create a new `MobiusWork` 
5. Verify that you can fill out all fields listed in the Acceptance Criteria of this ticket and can create the work successfully 
6. Verify that the fields properly display on the new work's show page 

# Notes

- `format` conflicts with an existing Hyrax method. It's underlying property name thusly won't be `format`. However, its label in the UI should be "Format" 
  - ~~Check #165 for what the property name should be~~ It should be `file_format`

**Comment by jillpe** [comment]
SoftServ QA
[Work](https://mobius-staging.staging.hykuup.com/concern/mobius_works/67fbc2c3-e59d-46a9-ae30-4f2f9a04bb25?locale=en)

The create work form does not have the `community` and `collection` fields. Everything else is there
<details><summary>Create Work Form</summary>


![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/84697174/47675ab0-418f-4d3f-8417-939ea098a63f)


</details>
