### ISSUE TITLE
Mobius (Bulkrax): assign proper work type based on tenant

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/hykuup_knapsack#168]
# Story

Ref: 
- #27 

Mobius has its own custom work types (see #166). Their imported CSVs do not specify which work type should be created, which means we need to designate one of the custom work types as a default. 

# Acceptance Criteria

- [ ] When importing into the Mobius tenant, the default work type should be `MobiusWork` 
- [ ] When importing into any tenant other than Mobius, the default work type should be `GenericWork` 

# Testing Instructions and Sample Files

_[Sample files](https://drive.google.com/drive/folders/1VZ5e-6psAPypp77P2AhY-0eOQg14Jpe4)_

-

# Notes

Should likely use either `HasLocalProcessing` or `Bulkrax.default_work_type`

**Comment by jillpe** [comment]
SoftServ QA: ✅ 

[Importer](https://mobius-staging.staging.hykuup.com/importers/3?locale=en)

Works came in as a mobius work
