### ISSUE TITLE
Mobius (Bulkrax): handle bs_isCollection and bs_isCommunity fields

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/hykuup_knapsack#169]
# Story

Ref:
- #27 

In mobius' CSVs, the `bs_isCollection` and `bs_isCommunity` columns represent whether the record should be a Collection or not. 

# Acceptance Criteria

- [ ] When importing into the Mobius tenant with a CSV that has a column named `bs_isCollection` with the value of `TRUE`, the data in that row should be used to create a Collection instead of a work 
- [ ] When importing into the Mobius tenant with a CSV that has a column named `bs_isCommunity` with the value of `TRUE`, the data in that row should be used to create a Collection instead of a work 
- [ ] Ensure that parent-child relationships still work as expected 
  - [ ] Child work, parent collection 
  - [ ] Child collection, parent collection 

# Testing Instructions and Sample Files

_The provided [sample files](https://drive.google.com/drive/folders/1VZ5e-6psAPypp77P2AhY-0eOQg14Jpe4) don't include an example of this data. A CSV will need to be created by hand to test_ 

1. 

# Notes

This was clarified in an email chain with the client. Jill has access if needed.

**Comment by laritakr** [comment]
Note: All collections currently are created as private (because the spreadsheet doesn't specify permissions). What is the desired behavior?

**Comment by jillpe** [comment]
SoftServ QA ✅ 

[Importer](https://mobius-staging.staging.hykuup.com/importers/3?locale=en)
