### ISSUE TITLE
Mobius (Bulkrax): properly attach files

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/hykuup_knapsack#170]
# Story

Ref:
- #27 

Mobius' ZIP imports don't format files in the way Bulkrax expects: 

- Bulkrax expects the zip to have a folder names `files/` that contains all the images 
  - Mobius zip files can contain multiple folders of files with names like `renamed_jpeg/`, `renamed_tiff/`, `renamed_pdf/`, etc 
- Bulkrax expects the CSV to specify which file should attach to the record using the `files` column 
  - Mobius CSVs don't have a column that specifies which files should attach to the record 

However, we can infer which files should attach to the record using the values in the `ss_pid` column: 
- Example `ss_pid`: `vital:10206` 
- Example matching filename: `vital_10206+SOURCE1+SOURCE1.0.jpeg`

# Acceptance Criteria

_In the following:_
- _`<X>` represents a uniquely identified numeric_ 
- _`<Y>` represents a file extension (e.g. `jpeg`, `tiff`, etc)_ 

- [ ] When importing a record with an `ss_pid` value of `vital:<X>`, the importer should search for a matching file with the name of `vital_<X>+SOURCE1+SOURCE1.0.<Y>` 
  - [ ] If the file is found, it should attach the file to the created work 
  - [ ] If the file is not found, it should log an error saying so on the record's entry 

# Testing Instructions and Sample Files

_[Sample files](https://drive.google.com/drive/folders/1VZ5e-6psAPypp77P2AhY-0eOQg14Jpe4)_

1. 

# Notes

**Comment by jillpe** [comment]
SoftServ QA ✅ 

[Importer](https://mobius-staging.staging.hykuup.com/importers/3?locale=en)
[Example work](https://mobius-staging.staging.hykuup.com/concern/mobius_works/e3c179fb-2ca6-4964-bca0-788850501850?locale=en)
