### ISSUE TITLE
Mobius (Bulkrax): properly attach thumbnails

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/hykuup_knapsack#171]
# Story

Ref:
- #27 
- #170 

In the [sample tar files](https://drive.google.com/drive/folders/1VZ5e-6psAPypp77P2AhY-0eOQg14Jpe4), some records appear to have thumbnails. ~~These thumbnails should be handled similarly to how we handle normal files (see #170).~~ Instead of using these, Hyku should generate new ones. 

# Acceptance Criteria

- [ ] Instead of using the provided thumbnails, Hyku should generate new ones based on the primary file(s) 

<details><summary>Archived</summary>

- [ ] When a matching thumbnail file is found, it should attach to the imported record 
  - [ ] Thumbnail derivative generation should be skipped for these records 
- [ ] When a matching thumbnail file is not found, one should be generated by Hyrax as normal 

</details>

# Testing Instructions and Sample Files

_[Sample files](https://drive.google.com/drive/folders/1VZ5e-6psAPypp77P2AhY-0eOQg14Jpe4)_

1. 

# Notes

Originally the plan was to use the provided thumbnails, but [not anymore](https://github.com/scientist-softserv/hykuup_knapsack/issues/171#issuecomment-2012701686).

**Comment by jillpe** [comment]
SoftServ QA: ✅ 



![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/84697174/f6ee2299-b44d-4e98-a81e-51f119a8ce55)
