### ISSUE TITLE
🐛 Works and Collections ingest as private regardless of Visibility seleciton

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#182]
### UPDATE: 
This issue is observed regardless if the work is imported or not. Repeating the following steps results in a failed update to the visibility property. And it seems as though it reverts back to whatever the original setting was. This needs to be addressed before Bulkrax. 

## STEPS TO REPRODUCE FROM RAILS CONSOLE

First, in the UI - login as an admin and create a work. Set the visibility to open.

```ruby
# find the work you just created
work = Hyrax.query_service.find_by(id: 'id123')

# check the visibility property then update it
work.visibility => 'open'
work.visibility = 'restricted'
Hyrax.persister.save(resource: work)

# check the UI. Did the property update? => no

# ask for visibility in rails console again to confirm that it updated
work.visibility => 'restricted' # this is mislead. Find the work again and ask for visibility

saved_work = Hyrax.query_service.find_by(id: 'id123')
saved_work.visibility => 'open' # it did not update as expected
```

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/e1a25a04-971b-41ce-bc7b-92d899dd9bc2)

Updating the visibility through the UI works though.

Original Issue: 
If you import a CSV on an importer and select the visibility to be open, it appears to ignore the selection. 

All imported works and collections get set to private. 

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/3c6ec0c4-a042-4c1e-bb39-5a78a2ebb989)

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/464f8963-d70d-41af-ae24-bffbbc2ed378)

# Acceptance Criteria

- [ ] We should be able to set the visibility of works and collections

**Comment by laritakr** [comment]
The visibility attribute is not part of collection, so calling save on collection doesn’t save it. It feels disingenuous to have a visibility= method on the collection because that doesn’t do what is needed, but that's a bit beside the point.

The FORM has the visibility tied in, and saves the Hyrax::AccessControl through the transaction, which is where it gets updated.

**Comment by ShanaLMoore** [comment]
problem - we need to change the form and not just the object. per LaRita

**Comment by laritakr** [comment]
Confirmed that it is now working after [a bulkrax update](https://github.com/samvera/bulkrax/commit/ba3d2d7bbce121c4502cb748ee1380e47e86d680).

**Comment by laritakr** [comment]
Verified that [Bulkrax update](d52800a3c899ed12f54d1d94c205bca73d98c712) fixed issue for collections. 

Tested via CSV 
[visibility.csv](https://github.com/scientist-softserv/hykuup_knapsack/files/14794289/visibility.csv)

Importer specified "Public" as default

Results:
![Screenshot 2024-03-28 at 2 55 43 PM](https://github.com/scientist-softserv/hykuup_knapsack/assets/17851674/fc735f85-663e-4bff-9b13-05fa2d7cc487)
