### ISSUE TITLE
Works with PDF file sets cannot be edited

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/hykuup_knapsack#185]
# Story

Currently, when navigating to the edit page of a work with a PDF fileset, we get an exception.  When it was first implemented, we added two checkboxes on the files tab of the edit form to control the showing of the PDF.js viewer and also Download PDF button.  These are no longer working in the Hyku Valkyrie upgrade.

# Acceptance Criteria

- [ ] Admins can navigate to the edit page of a work with a PDF fileset
- [ ] PDF.js loads the PDF on the work's show page if selected as the option.
- [ ] The Download PDF and Show PDF Viewer buttons both work as intended

# Screenshots / Video

<img width="818" alt="image" src="https://github.com/scientist-softserv/hykuup_knapsack/assets/19597776/610fd6cf-a8cb-4945-a8a4-6ce862dbb1f9">

# Testing Instructions and Sample Files

- [ ] Create a work with a PDF file
- [ ] After ingest, view the work and observe that PDF.js loads it correctly
- [ ] Edit the work
  - [ ] Toggle both the show pdf viewer and download pdf buttons to see they work properly

**Comment by ShanaLMoore** [comment]
This ticket is not a bug. PDF.js was never fully implemented for valkyrie

**Comment by ShanaLMoore** [comment]
After discussing with the team, we will proceed by showing the pdf.js based on the flip flop instead of the property values. 

We will revisit fixing the actual implementation in the future, probably when we start the iiif print x valkyrie epic.

**Comment by jillpe** [comment]
SoftServ QA: ✅ 
Was able to edit using the edit form and it saved

[Work](https://demo.staging.hykuup.com/concern/mobius_works/2f8b8a3a-908a-4639-9184-48c161a7194c?locale=en)

**Comment by jillpe** [comment]
Note, we had to disable the toggle buttons specified above, so those are not a part of this ticket
