### ISSUE TITLE
🐛 deleting Valkyrie objects

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#187]
# Summary

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/2b516131-2515-40ba-bf80-2edc27283799)

# Acceptance Criteria

- [ ] Deleting a collection completes normally and leaves no stray objects
- [ ] Deleting a work completes normally and leaves no stray objects (file set(s) are also deleted)
- [ ] Deleting a file set completes normally and leaves no stray objects

# Testing Instructions
- Delete a collection. It completes normally.
- Delete a work. It completes normally
    - Open a work. 
    - In another tab, open its file set using the 'xxxx/file_sets/:id' route rather than the 'xxxx/concern/parent/:work_id/file_sets/:id' route
    - Delete the work from that tab
    - Refresh the file set tab. 
    - See that the file set returns a not found error
- Delete a file set. It completes normally

# Note
Verifying that all objects are removed along with the work or file set is a bit more complicated. It can be done via the rails console if desired using the following commands:

```
wk =  Hyrax.query_service.find_by(id: work_id)
fs = wk.members.first
wk_access = Hyrax::AccessControl.for(resource: wk)
fs_access = Hyrax::AccessControl.for(resource: fs)
fs_metadata = Hyrax.query_service.find_by(id: fs.file_ids.first)
```

**Comment by laritakr** [comment]
# Notes

Tested locally via the UI and rails console. Works after iiif_print update.
