### ISSUE TITLE
:bug: Solr url is intermittently wrong

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#194]
This manifests on staging and locally. hyrax-valkyrie should be a tenant. 

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/66f431a1-18d3-4cf4-b5ed-725e87c04570)

There are two inter-related functions/files regarding how we manage switching:

- [Valkyrie::Indexing::Solr::IndexingAdapter#connection_url](https://github.com/samvera/hyrax/blob/a5a0ae9e56df857a92fc53ae86216cbb007db47a/lib/valkyrie/indexing/solr/indexing_adapter.rb#L83-L101)
- [SolrEndpoint](https://github.com/samvera/hyku/blob/5b612356726929b53f45ce9a8be48dc9eb5463fb/app/models/solr_endpoint.rb#L13-L38)

We may not have the timing/sequencing of those quite correct.

**Comment by laritakr** [comment]
Further addressed by https://github.com/samvera/hyku/issues/2177
