### ISSUE TITLE
:gift: Add custom rubocop rule to double combo

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#199]
# Summary

ref: https://assaydepot.slack.com/archives/C0313NKG2DA/p1712176060340309
![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/9713c8a3-b0b8-4833-96eb-135d1b3e2ad6)

# Notes
https://github.com/samvera/hyrax/pull/6221/files

**Comment by kirkkwang** [comment]
https://github.com/samvera/hyrax/commit/ef2ffa446fc1fccfa36793d2ba0404931dd35ce8
