### ISSUE TITLE
:bug: Valkyrie: double_combo FileSet Derivatives don't get copied over

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#206]
# Summary
⚠️  ~~Reference [this branch](https://github.com/samvera/hyku/issues/2194) for your base, if it hasn't already been merged into main.~~ ⚠️ [ this branch has since been merged ]

While LaRita was working on the derivative issues in IiifPrint, she noticed that we missed the mark when implementing file sets for valkyrie in the double_combo! 

Currently, we are copying over the thumbnail for the fileset but none of its derivatives. That means that they will be lost during the lazy migration (fedora => valkyrie on a record save). We must fix this.

Collection thumbnails (currently handled about the same as a derivative) should be migrated via a rake task, as Collection thumbnails are no longer supported in Hyrax.

Hopefully we can leverage what LaRita has learned by working on this ticket: 
- [x] https://github.com/scientist-softserv/iiif_print/issues/350

# Acceptance Criteria

- [ ] Fedora based derivatives should be transferred to valkyrie objects, when a user edits/saves a pre-existing fedora record. 

# Screenshots or Video

# Testing Instructions

# Notes

this is a duplicate of https://github.com/samvera/hyrax/issues/6791 - the work will need to go into Hyrax.

**Comment by ShanaLMoore** [comment]
update freya adapater to find the derivatives in addition to the thumbnails.

**Comment by laritakr** [comment]
https://github.com/samvera/hyrax/pull/6807
