### ISSUE TITLE
Collection thumbnail migrations

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#214]
# Summary

We need a rake task to migrate collection thumbnails. This applies to pals and Adventist

# Acceptance Criteria

- [ ] Running the rake task will convert an ActiveFedora (AF) Collection into a Collection Resource.
- [ ] Running the rake task should persist any thumbnail the AF Collection had.

# Screenshots or Video

# Testing Instructions
- ~verify a collection with a thumbnail, after editing, still has a thumbnail~
- Dev to run rake task for confirmation that any pre existing collection thumbnails persist

# Notes
We made a similar rake task for this but it is untested:

- [This](https://github.com/samvera/hyku/blob/main/lib/tasks/migrate_hyku_commons_collection_thumbnails_to_valkyrie.rake) should probably be removed from Hyku and put into pals knapsack

**Comment by jillpe** [comment]
we will be migrating 2 tenants from Hyku Commons to pals knapsack staging

**Comment by ShanaLMoore** [comment]
find a tenant in staging with a collections that have thumbnails

**Comment by jillpe** [comment]
SoftServ QA: ✅ 

[Collection](https://demo.hyku-demo.notch8.cloud/dashboard/collections/6e354675-b509-44bf-a7f7-dfcf0fa23012?locale=en)


**Before Editing**
![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/84697174/6dead2e0-4cdd-4011-ab3e-b6c1c7c3fc31)

** After Editing**


![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/84697174/1e28fd61-410f-4c2e-989b-2b1da40e7dc4)

**Comment by ShanaLMoore** [comment]
Hi @jillpe I think demo is an account we use so I would test this on one of the client's staging accounts.

**Comment by ShanaLMoore** [comment]
And actually, i think the rake task currently only applies to pals. moving back to dev for further review.

**Comment by ShanaLMoore** [comment]
Rob is moving prod data into pals staging so this would be a great time to test.

**Comment by ShanaLMoore** [comment]
How to get local pre valkyrie data: https://assaydepot.slack.com/archives/C0311DN2YCA/p1721771295691059


![Image](https://github.com/user-attachments/assets/cc492396-d48b-43b6-a558-0c21b0dd669d)

**Comment by ShanaLMoore** [comment]
ref: https://github.com/samvera/hyku/pull/2273#pullrequestreview-2228531557

This is no longer needed and has been removed from Hyku
