### ISSUE TITLE
'View all collection' button is not working

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/hykuup_knapsack#226]
## Summary
The view all collection button on the home page of a tenant is not working. 

Example: [Mobius](http://covenant.hykuup.com)
Example of End Goal: [Hyku Commons](https://demo.hykucommons.org/)

## Acceptance Criteria
- [ ] The 'View all collections' button should take the user to a catalog search with all of the collections

**Comment by jillpe** [comment]
QA blocked until specs are passing

**Comment by ShanaLMoore** [comment]
BLOCKED: this has been merged into hyku but not in the knapsack yet.

**Comment by jillpe** [comment]
SoftServ QA: ✅ 


https://github.com/scientist-softserv/hykuup_knapsack/assets/84697174/b30d4647-ea5c-4c2f-8f93-262e450fa089
