### ISSUE TITLE
Contribute back to HykuKnapsack

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/hykuup_knapsack#232]
# Story

With the development of Pals Knapsack, we've done a lot of things that should be contributed back to HykuKnapsack.

# Acceptance Criteria

- [x] update the generator
  - [x] include the video validation line
  - [x] change the parent class the form inherits from
  - [x] not generate the controllers for "SomethingResource"
  - [x] indexers need to also `include HykuIndexing`
  - [x] change the parent class the indexer inherits from
  - [x] adjust indexer spec
- [x] update the `HykuKnapsack::Engine`
- [x] update the `rails_helper.rb`
- [x] wrap hyrax initializer in an `after_initialize`
- [ ] ~add symlink in `Dockerfile` for branding~ (this should be in Hyku)
- [x] update Hyku submodule
- [x] update `Gemfile.lock`

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by ShanaLMoore** [comment]
blocked by hyku v6.0 release
