### ISSUE TITLE
Review all jobs and reconcile with upstream changes

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#40]
# Summary
Goal: Assess any changes to hyrax code versus files we find. 

# Acceptance Criteria

- [ ] Jobs are for upstream changes

## Notes

- [x] app/jobs/lease_auto_expiry_job.rb
- [x] app/jobs/delete_old_guests_job.rb
- [x] app/jobs/import_work_from_purl_job.rb
- [x] app/jobs/reindex_admin_sets_job.rb
- [x] app/jobs/reindex_item_job.rb
- [x] app/jobs/reindex_works_job.rb
- [x] app/jobs/remove_solr_collection_job.rb
- [x] app/jobs/create_redis_namespace_job.rb
- [x] app/jobs/create_account_inline_job.rb
- [x] app/jobs/cleanup_account_job.rb
- [x] app/jobs/create_solr_collection_job.rb
- [x] app/jobs/create_fcrepo_endpoint_job.rb
- [x] app/jobs/application_job.rb
- [x] app/jobs/embargo_auto_expiry_job.rb
- [x] app/jobs/reindex_collections_job.rb
- [x] app/jobs/create_default_admin_set_job.rb
- [x] app/jobs/reindex_file_sets_job.rb

ref: [GBH](https://github.com/scientist-softserv/ams/issues/26)

**Comment by kirkkwang** [comment]
All jobs reviewed, nothing suspicious, cleanup_account_job does have failing specs at the moment but will be addressed in specs ticket
