### ISSUE TITLE
Admin Invite Email not Received

### ISSUE THREAD

**Issue by DraxIndustries79** [scientist-softserv/hykuup_knapsack#6]
## Story
Currently, using the workflow on the Manage Account page to invite kevinkochanski@scientist.com as an Admin to kevin-test-aug-23.hykuup.com I did not receive the email (checked spam).

![Image](https://user-images.githubusercontent.com/37004183/257869374-56ee1893-a4f6-474b-ab69-fdcef0005b89.png)

## Acceptance
- [ ] Email needs to be set up for admin invites

**Comment by jillpe** [comment]
Most likely and email credential issue

**Comment by kirkkwang** [comment]
Blocked until Rob makes sure all the changes he had to make get consolidated properly

**Comment by jillpe** [comment]
No longer blocked
